clc;
clear all;
close all;
fp=input('Enter passband frequency in Hz: ');
fs=input('Enter stopband frequency in Hz: ');
ff=input('Enter sampling frequency in Hz: ');
ap = input('passband gain in dB: ');
as = input('stopband attenuat in dB: ');
wp = 2*pi*(fp/ff);
ws = 2*pi*(fs/ff);
up = 2*tan(wp/2);
us = 2*tan(ws/2);
[n, wc]=buttord(up, us, ap, as, 's');
disp('order of filter is: ');
disp(n);
disp('Normalised frequency is: ');
disp(wc);
[num, den] = butter(n, wc, 's');
[b,a] = bilinear(num, den, 1);
freqz(b, a, 512, ff);
printsys(b,a,'z');
