clc;
clear all;
close all;
f = input('Enter frequency: ');
fs = input('Sampling Frequency: ');
N = input('Order of filter: ');
wc = 2*pi*(f/fs);
h= fir1(N-1, wc/pi, hamming (N));
disp('hamming window coefficients: ');
disp(hamming(N));
disp('impulse response of the FIR filter: ');
disp(h);
figure(1);
freqz(h);
figure(2);
n = 0:1:N-1;
stem(n,h);
xlabel('n');
ylabel('h(n');
title('impulse response of the FIR filter');
