clc;
clear all;
close all;
final = 0.05;
t = 0:0.00005:final;
fd = input('Enter analog frequency: ');
xt = sin(2*pi*fd*t);
fs1 = 1.3 * fd;
n1 = 0:1/fs1:final;
xn = sin(2*pi*fd*n1);
subplot(3,1,1);
plot(t, xt, n1, xn, 'r*-');
xlabel('time division axis');
ylabel('amplitude div axis');
title('undersampling');
fs2 = 2.0 * fd;
n2 = 0:1/fs2:final;
xn = sin(2*pi*fd*n2);
subplot(3,1,2);
plot(t, xt, n2, xn, 'r*-');
xlabel('time division axis');
ylabel('amplitude div axis');
title('nyquiest rate');
fs3 = 3 * fd;
n3 = 0:1/fs3:final;
xn = sin(2*pi*fd*n3);
subplot(3,1,3);
plot(t, xt, n3, xn, 'r*-');
xlabel('time division axis');
ylabel('amplitude div axis');
title('oversampling');
