clc;
close all;
clear all;
syms n;
a = 2;
x = a^n;
X = ztrans(x);
disp('Z Transform of a^n, a > 1');
disp(X);
syms n;
a = 0.5;
x = a^n;
X1 = ztrans(x);
disp('Z Transform of a^n, 1 > a > 0');
disp(X1);
syms n;
x = n+1;
X2 = ztrans(x);
disp('Z transformation of 1+n');
disp(X2);
A = iztrans(X);
disp('Inverse Z Transform of a^n, a > 1: ');
disp(A);
B = iztrans(X1);
disp('Inverse Z Transform of a^n, 0 > a > 1: ');
disp(B);
C = iztrans(X2);
disp('Inverse Z Transform of 1+n: ');
disp(C);
subplot(3,1,1);
zplane([1 0], [1 -2]);
subplot(3,1,2);
zplane([1 0], [1 -1/2]);
subplot(3,1,3);
zplane([1 0 0], [1 -2 1]);
